# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hanak/Documents/GitHub/qick/firmware/fft_correlator/fft_correlator.srcs/sources_1/ip/zynq_ultra_ps_e_0/zynq_ultra_ps_e_0.xci
# IP: The module: 'zynq_ultra_ps_e_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hanak/Documents/GitHub/qick/firmware/fft_correlator/fft_correlator.gen/sources_1/ip/zynq_ultra_ps_e_0/zynq_ultra_ps_e_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ultra_ps_e_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hanak/Documents/GitHub/qick/firmware/fft_correlator/fft_correlator.gen/sources_1/ip/zynq_ultra_ps_e_0/zynq_ultra_ps_e_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ultra_ps_e_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/hanak/Documents/GitHub/qick/firmware/fft_correlator/fft_correlator.srcs/sources_1/ip/zynq_ultra_ps_e_0/zynq_ultra_ps_e_0.xci
# IP: The module: 'zynq_ultra_ps_e_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hanak/Documents/GitHub/qick/firmware/fft_correlator/fft_correlator.gen/sources_1/ip/zynq_ultra_ps_e_0/zynq_ultra_ps_e_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ultra_ps_e_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hanak/Documents/GitHub/qick/firmware/fft_correlator/fft_correlator.gen/sources_1/ip/zynq_ultra_ps_e_0/zynq_ultra_ps_e_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ultra_ps_e_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
